package AprovadoApp;

/**
* AprovadoApp/AprovadoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aprovado.idl
* Sexta-feira, 5 de Outubro de 2018 12h29min10s BRT
*/

public final class AprovadoHolder implements org.omg.CORBA.portable.Streamable
{
  public AprovadoApp.Aprovado value = null;

  public AprovadoHolder ()
  {
  }

  public AprovadoHolder (AprovadoApp.Aprovado initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AprovadoApp.AprovadoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AprovadoApp.AprovadoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AprovadoApp.AprovadoHelper.type ();
  }

}
