package AprovadoApp;


/**
* AprovadoApp/AprovadoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aprovado.idl
* Sexta-feira, 5 de Outubro de 2018 12h29min10s BRT
*/

abstract public class AprovadoHelper
{
  private static String  _id = "IDL:AprovadoApp/Aprovado:1.0";

  public static void insert (org.omg.CORBA.Any a, AprovadoApp.Aprovado that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AprovadoApp.Aprovado extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AprovadoApp.AprovadoHelper.id (), "Aprovado");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AprovadoApp.Aprovado read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AprovadoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AprovadoApp.Aprovado value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AprovadoApp.Aprovado narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AprovadoApp.Aprovado)
      return (AprovadoApp.Aprovado)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AprovadoApp._AprovadoStub stub = new AprovadoApp._AprovadoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AprovadoApp.Aprovado unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AprovadoApp.Aprovado)
      return (AprovadoApp.Aprovado)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AprovadoApp._AprovadoStub stub = new AprovadoApp._AprovadoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
