package AprovadoApp;


/**
* AprovadoApp/AprovadoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aprovado.idl
* Sexta-feira, 5 de Outubro de 2018 12h29min10s BRT
*/

public interface AprovadoOperations 
{
  int aprovar (double n1, double n2, double n3);
  void shutdown ();
} // interface AprovadoOperations
