package AprovadoApp;


/**
* AprovadoApp/Aprovado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aprovado.idl
* Sexta-feira, 5 de Outubro de 2018 12h29min10s BRT
*/

public interface Aprovado extends AprovadoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Aprovado
