package SalarioApp;


/**
* SalarioApp/SalarioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SalarioApp.idl
* Sexta-feira, 5 de Outubro de 2018 11h38min02s BRT
*/

public interface SalarioOperations 
{
  double novoSal1 (double sal);
  double novoSal2 (double sal);
  void shutdown ();
} // interface SalarioOperations
