package SalarioApp;


/**
* SalarioApp/SalarioHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SalarioApp.idl
* Sexta-feira, 5 de Outubro de 2018 11h38min02s BRT
*/

abstract public class SalarioHelper
{
  private static String  _id = "IDL:SalarioApp/Salario:1.0";

  public static void insert (org.omg.CORBA.Any a, SalarioApp.Salario that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SalarioApp.Salario extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SalarioApp.SalarioHelper.id (), "Salario");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SalarioApp.Salario read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SalarioStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SalarioApp.Salario value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SalarioApp.Salario narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SalarioApp.Salario)
      return (SalarioApp.Salario)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SalarioApp._SalarioStub stub = new SalarioApp._SalarioStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SalarioApp.Salario unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SalarioApp.Salario)
      return (SalarioApp.Salario)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SalarioApp._SalarioStub stub = new SalarioApp._SalarioStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
