package nadadorApp;


/**
* nadadorApp/nadadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from nadador.idl
* Sexta-feira, 5 de Outubro de 2018 13h04min05s BRT
*/

public interface nadadorOperations 
{
  String pesoF (int idade);
  void shutdown ();
} // interface nadadorOperations
