package nadadorApp;


/**
* nadadorApp/nadadorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from nadador.idl
* Sexta-feira, 5 de Outubro de 2018 13h04min05s BRT
*/

public abstract class nadadorPOA extends org.omg.PortableServer.Servant
 implements nadadorApp.nadadorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("pesoF", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // nadadorApp/nadador/pesoF
       {
         int idade = in.read_long ();
         String $result = null;
         $result = this.pesoF (idade);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // nadadorApp/nadador/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:nadadorApp/nadador:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public nadador _this() 
  {
    return nadadorHelper.narrow(
    super._this_object());
  }

  public nadador _this(org.omg.CORBA.ORB orb) 
  {
    return nadadorHelper.narrow(
    super._this_object(orb));
  }


} // class nadadorPOA
