package nadadorApp;

/**
* nadadorApp/nadadorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from nadador.idl
* Sexta-feira, 5 de Outubro de 2018 13h04min05s BRT
*/

public final class nadadorHolder implements org.omg.CORBA.portable.Streamable
{
  public nadadorApp.nadador value = null;

  public nadadorHolder ()
  {
  }

  public nadadorHolder (nadadorApp.nadador initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nadadorApp.nadadorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nadadorApp.nadadorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nadadorApp.nadadorHelper.type ();
  }

}
