package nadadorApp;


/**
* nadadorApp/nadador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from nadador.idl
* Sexta-feira, 5 de Outubro de 2018 13h04min05s BRT
*/

public interface nadador extends nadadorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface nadador
