package nadadorApp;


/**
* nadadorApp/nadadorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from nadador.idl
* Sexta-feira, 5 de Outubro de 2018 13h04min05s BRT
*/

abstract public class nadadorHelper
{
  private static String  _id = "IDL:nadadorApp/nadador:1.0";

  public static void insert (org.omg.CORBA.Any a, nadadorApp.nadador that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nadadorApp.nadador extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (nadadorApp.nadadorHelper.id (), "nadador");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nadadorApp.nadador read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_nadadorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nadadorApp.nadador value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static nadadorApp.nadador narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof nadadorApp.nadador)
      return (nadadorApp.nadador)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      nadadorApp._nadadorStub stub = new nadadorApp._nadadorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static nadadorApp.nadador unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof nadadorApp.nadador)
      return (nadadorApp.nadador)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      nadadorApp._nadadorStub stub = new nadadorApp._nadadorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
