package MaioridadeApp;


/**
* MaioridadeApp/Maioridade.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Maioridade.idl
* Sexta-feira, 5 de Outubro de 2018 12h03min27s BRT
*/

public interface Maioridade extends MaioridadeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Maioridade
