package pesoApp;


/**
* pesoApp/pesoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from peso.idl
* Sexta-feira, 5 de Outubro de 2018 12h51min06s BRT
*/

abstract public class pesoHelper
{
  private static String  _id = "IDL:pesoApp/peso:1.0";

  public static void insert (org.omg.CORBA.Any a, pesoApp.peso that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pesoApp.peso extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (pesoApp.pesoHelper.id (), "peso");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pesoApp.peso read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_pesoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pesoApp.peso value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static pesoApp.peso narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof pesoApp.peso)
      return (pesoApp.peso)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      pesoApp._pesoStub stub = new pesoApp._pesoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static pesoApp.peso unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof pesoApp.peso)
      return (pesoApp.peso)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      pesoApp._pesoStub stub = new pesoApp._pesoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
