package pesoApp;


/**
* pesoApp/pesoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from peso.idl
* Sexta-feira, 5 de Outubro de 2018 12h51min06s BRT
*/

public interface pesoOperations 
{
  double pesoF (double altura);
  double pesoM (double altura);
  void shutdown ();
} // interface pesoOperations
