package pesoApp;

/**
* pesoApp/pesoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from peso.idl
* Sexta-feira, 5 de Outubro de 2018 12h51min06s BRT
*/

public final class pesoHolder implements org.omg.CORBA.portable.Streamable
{
  public pesoApp.peso value = null;

  public pesoHolder ()
  {
  }

  public pesoHolder (pesoApp.peso initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pesoApp.pesoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pesoApp.pesoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pesoApp.pesoHelper.type ();
  }

}
