package pesoApp;


/**
* pesoApp/peso.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from peso.idl
* Sexta-feira, 5 de Outubro de 2018 12h51min06s BRT
*/

public interface peso extends pesoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface peso
