package pesoApp;


/**
* pesoApp/pesoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from peso.idl
* Sexta-feira, 5 de Outubro de 2018 12h51min06s BRT
*/

public abstract class pesoPOA extends org.omg.PortableServer.Servant
 implements pesoApp.pesoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("pesoF", new java.lang.Integer (0));
    _methods.put ("pesoM", new java.lang.Integer (1));
    _methods.put ("shutdown", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // pesoApp/peso/pesoF
       {
         double altura = in.read_double ();
         double $result = (double)0;
         $result = this.pesoF (altura);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // pesoApp/peso/pesoM
       {
         double altura = in.read_double ();
         double $result = (double)0;
         $result = this.pesoM (altura);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // pesoApp/peso/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pesoApp/peso:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public peso _this() 
  {
    return pesoHelper.narrow(
    super._this_object());
  }

  public peso _this(org.omg.CORBA.ORB orb) 
  {
    return pesoHelper.narrow(
    super._this_object(orb));
  }


} // class pesoPOA
