package MaioridadeApp;

/**
* MaioridadeApp/MaioridadeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Maioridade.idl
* Sexta-feira, 5 de Outubro de 2018 12h03min27s BRT
*/

public final class MaioridadeHolder implements org.omg.CORBA.portable.Streamable
{
  public MaioridadeApp.Maioridade value = null;

  public MaioridadeHolder ()
  {
  }

  public MaioridadeHolder (MaioridadeApp.Maioridade initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaioridadeApp.MaioridadeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaioridadeApp.MaioridadeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaioridadeApp.MaioridadeHelper.type ();
  }

}
