package MaioridadeApp;


/**
* MaioridadeApp/MaioridadeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Maioridade.idl
* Sexta-feira, 5 de Outubro de 2018 12h03min27s BRT
*/

public interface MaioridadeOperations 
{
  int maioridadeF (int idade);
  int maioridadeM (int idade);
  void shutdown ();
} // interface MaioridadeOperations
