package MaioridadeApp;


/**
* MaioridadeApp/MaioridadeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Maioridade.idl
* Sexta-feira, 5 de Outubro de 2018 12h03min27s BRT
*/

abstract public class MaioridadeHelper
{
  private static String  _id = "IDL:MaioridadeApp/Maioridade:1.0";

  public static void insert (org.omg.CORBA.Any a, MaioridadeApp.Maioridade that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MaioridadeApp.Maioridade extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MaioridadeApp.MaioridadeHelper.id (), "Maioridade");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MaioridadeApp.Maioridade read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MaioridadeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MaioridadeApp.Maioridade value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MaioridadeApp.Maioridade narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MaioridadeApp.Maioridade)
      return (MaioridadeApp.Maioridade)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MaioridadeApp._MaioridadeStub stub = new MaioridadeApp._MaioridadeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MaioridadeApp.Maioridade unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MaioridadeApp.Maioridade)
      return (MaioridadeApp.Maioridade)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MaioridadeApp._MaioridadeStub stub = new MaioridadeApp._MaioridadeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
